route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname, instance, container_name]

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: '{YOUR_BOT_TOKEN}'
        chat_id: -YOUR_GROUP_CHAT_ID
        parse_mode: 'Markdown'
        message: >
          !!!! Alerts Firing !!!! {{ Labels.alertname }}
