global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9097'

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - '185.244.183.200:26660'

  - job_name: 'validators'
    scrape_interval: 15s
    metrics_path: /metrics/validators
    static_configs:
      - targets:
        - '185.244.183.200:9300'
