{
 "title": "Cosmos Node Stats",
 "description": "Stats of a Cosmos fullnode",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node catching up?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tendermint_node_catching_up", "legendFormat": "{{ host }} @ {{ instance }} " }
   ]
  },
  {
   "title": "version mismatch?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg(tendermint_latest_version_mismatch) by (host, instance)",
     "legendFormat": "{{ host }} @ {{ instance }} "
    }
   ]
  },
  {
   "title": "blocks diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(tendermint_remote_node_latest_block) by (host, instance) - avg(tendermint_local_node_latest_block) by (host, instance)",
     "legendFormat": "{{ host }} "
    }
   ]
  },
  {
   "title": "voting power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "tendermint_node_voting_power", "legendFormat": "{{ host }} " }
   ]
  },
  {
   "title": "versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tendermint_latest_version_mismatch"
    }
   ]
  }
 ]
}